import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const metadata = JSON.parse(await fs.readFile(path.join(root, 'assets/materials.json'), 'utf8'));
const extensions = new Set(['.pdf', '.html', '.htm', '.md', '.txt', '.docx', '.pptx', '.xlsx', '.zip']);
async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(entries.sort((a,b)=>a.name.localeCompare(b.name)).map(async entry => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  }));
  return nested.flat();
}
const items = [];
for (const full of await walk(path.join(root, 'files'))) {
  const file = path.relative(root, full).split(path.sep).join('/');
  const ext = path.extname(file).toLowerCase();
  // The inherited sample is a reader fixture, not study material.
  if (!extensions.has(ext) || file === 'files/wlsa-sample.pdf' || file.endsWith('/README.md')) continue;
  const info = metadata.files[file] || {};
  const course = metadata.courses.find(c => c.id === info.course || c.folder === file.split('/')[1]);
  const stat = await fs.stat(full);
  const href = './' + file.split('/').map(encodeURIComponent).join('/');
  items.push({
    id: info.id || 'file-' + createHash('sha256').update(file).digest('hex').slice(0, 16),
    title: info.title || path.basename(file, ext).replace(/[_-]/g, ' ').trim(),
    author: info.author || '', subject: info.subject || course?.subject || 'General',
    course: course?.id || '', type: info.type || 'Review Guide',
    description: info.description || '', keywords: info.keywords || course?.keywords || [],
    source: course?.title || 'Study materials', format: ext.slice(1).toUpperCase(),
    file, href, ...(ext === '.pdf' ? {pdf:href} : {}),
    size: stat.size, updated: info.updated || '', available: true
  });
}
const placeholders = metadata.courses.filter(c => !items.some(i => i.course === c.id)).map(c => ({
  ...c, type:'Review Guide', source:'Course collection', author:'', available:false, format:''
}));
const data = `// Generated by scripts/build-catalog.mjs. Edit materials.json or add files, then rebuild.\nwindow.ARCHIVE_COURSES = ${JSON.stringify(metadata.courses,null,2)};\nwindow.ARCHIVE_ITEMS = ${JSON.stringify([...items,...placeholders],null,2)};\n`;
await fs.writeFile(path.join(root,'assets/data.js'),data);
console.log(`Indexed ${items.length} files; ${placeholders.length} course collections awaiting uploads.`);
